Ada-Developers-Academy/core-unit-1

- functions-continued/how-to-read-documentation.md
Content on How to Read Docs. This gets introduced after functions.
> How to Read Docs: Content

- what-is-software-development/activity-intention-setting-our-careers.instructor.md
- what-is-software-development/activity-intention-setting-our-careers.md
- what-is-software-development/activity-study-plan.instructor.md
- what-is-software-development/activity-study-plan.md
- what-is-software-development/study-like-a-programmer.md
- what-is-software-development/what-is-software.md
This is "day 2" stuff, so this content is about getting folks to really think about the possibilities of software.
> What is Software Development? Content, activities, instructor guides

- config.yaml
- while-loops/while-loops.md
Priority is to review the content (words!)
Examples and questions still need to be filled out.
- Open to suggestions on examples and questions
> while-loops: Content

- approaching-a-problem/activity-breaking-down-a-problem.instructor.md
- approaching-a-problem/activity-breaking-down-a-problem.md
- approaching-a-problem/breaking-down-a-problem.md
Content on Breaking Down a Problem.
> Breaking down a problem: Content

- fundamentals-recap/conditionals-recap.md
- fundamentals-recap/fundamentals-vocabulary.md
- fundamentals-recap/practice-conditionals-recap.md
- fundamentals-recap/practice-fundamentals-vocabulary.md
Content is there. Written to be a "reference" or "cheat sheet," as this is material that they have already covered.
Worksheets need to be filled out, although I've written an outline for the ideal number and kind of questions
> Fundamentals Recap: Content and Activity Guidelines

- iterating-over-data/intro-to-iteration.md
- iterating-over-data/iterating-and-special-cases.md
- iterating-over-data/iterating-over-dictionaries.md
- iterating-over-data/iterating-over-lists.md
Order is:
1. Intro to Iteration
2. Iterating over Lists
3. Iterating over Dictionaries
4. Iterating and Special Cases
> iterating-over-data: ports from old core repo

- fundamentals-recap/fundamentals-vocabulary.md
Small edits to Fundamentals-recap such as:
- Adding output of print statements (don't have to take on my format, this is just to get ourselves thinking about whether it's important to display output from print statements)
- Spelling/Grammar fixes
> WIP: edits to fundamentals-recap

- iterating-over-data/practice-iterating-over-data.md
One thing to look over: Question 7. We show an example of a `for-else` loop using print statements and a break case; however, this can also be done with a `return` statement, which is how my test is set up. Seems more likely they will be using `return` statements instead of print and break cases.
> Practice iterating over data

- composition/composition.md
- intro-to-oop-relationships/inheritance.md
- added one-to-one and one-to-many vocabulary
- added a couple comprehensions questions about the Product and ShoppingCart example
> Be/one to one/many

- while-loops/while-loops.md
> added while-loops playlist

- iterating-over-data/iterating-over-dictionaries.md
- iterating-over-data/iterating-over-lists.md
Checked videos in preview. Looks good.
> embedded videos to dictionaries and lists

- intro-to-debugging/intro-to-errors.md
> change sum() to add_together()

- big-o/problem-set-big-o.md
Pretty much a direct translation from these two resources from textbook-curriculum. Edited into Python, made cosmetic formatting changes, spliced in the explanations into the explanations, but didn't really change anything else.
https://github.com/gSchool/ada-cs-fun-class/blob/master/02-arrays-and-efficiency/04-time-complexity-quiz.md
https://github.com/Ada-Developers-Academy/textbook-curriculum/blob/master/04-cs-fundamentals/classroom/time%20complexity/time_complexity_quiz_solutions.md
> problem-set-big-o

- functions-continued/problem-set-functions-continued.md
"(short for candidate)" doesn't seem necessary? I could be wrong
> Removed unnecessary parenthesis detail about an abbreviation for candidate

- intro-to-tests/problem-set-intro-to-pytest.md
We might want to wait until C16 to merge this but I figured having the PR could be handy.
> Don't highlight stack traces as bash

- nested-data-and-nested-loops/nested-lists-and-dictionaries.md
meant to include this in the previous fix.  noticed by a student so I'm going to put this in right away!
> Fix the count of elements

- while-loops/problem-set-while-loops.md
noticed the sidewinder caption formatting had also gone "off"
> fix while problem set again: caption formatting

- intro-to-oop-relationships/problem-set-oop-relationships.md
- the Bear ctor needs to super to Mammal or else the fields on self won't get set
> add minimal question correction

- debugging-contd/debugging-contd.md
- debugging-contd/problem-set-debugging-contd.md
Added debugger video and the code I used for the debugger lesson.  We could do a separate lesson on this later if needed.
> using the debugger video

- intro-to-oop-relationships/super.md
I'd _really_ like us to stay away from multiple-inheritance discussions. Even with Python's official support for it (and mixins) it's still non-trivial to get right, and not something a junior dev needs to be thinking about.
I reworked the sample code to show reasons to use super in constructors as well as regular instance methods. I added some CFU questions that reinforce the ctor usage, and discourages using super when it's not needed.
I think this lesson provides enough of a justification for using super (especially if we avoid introducing some of the alternatives), so hopefully this is helpful!
> modifications to de-emphasize multiple inheritance

- intro-to-oop-contd/testing-objects.md
Cherise noticed that the answers for challenge two were incorrect/unclear. I put in her corrections.
> Update challenge 2 in testing objects

- approaching-a-problem/pseudocode-and-logic.md
- intro-to-debugging/intro-to-debugging.md
- iterating-over-data/iterating-over-dictionaries.md
- iterating-over-data/iterating-over-lists.md
- nested-data-and-nested-loops/nested-lists-and-dictionaries.md
- what-is-software-development/what-is-software.md
**Changes:**
- _pseudocode-and-logic.md_: Update line where I was unclear what 'all of these' referred to.
- _what-is-software.md_: Change the phrase 'your own very computer' to 'your very own computer'.
- _intro-to-debugging.md_: Removed a sentence in the'How do we fix it?' section that was missing punctuation and reiterated what was directly above it. 
- _iterating-over-dictionaries.md_: Add a little clarification that we're talking about looping over key/value pairs in the section 'About .items()'.
- _iterating-over-lists.md_: update examples 2 & 3 in the table for 'Dining Out Explained' to add the missing 'tonight' at the end of the sentence.
- _nested-lists-and-dictionaries.md_: changed a '.' to a ':' for consistency.
**Questions**
- I removed a sentence in intro-to-debugging.md that …
> Small updates across Unit 1

- what-is-software-development/study-like-a-programmer.md
PR to address this feedback: https://app.asana.com/0/1201700438643002/1201932913984494/f
> change suggestion from pre-read

- .gitignore
- intro-to-oop-relationships/problem-set-oop-relationships.md
to address this asana task: https://app.asana.com/0/1201700438643002/1202067551873975/f
To review: 
* `git fetch origin pull/179/head:be/oop-ps`
* `git checkout be/oops-ps`
* `learn preview .`
* Test OOP Relationships Problem Set Question 5
> restore wrong answer in oop-relationships problem set

- code_samples.py
- fundamentals/conditionals.md
To address this Asana task: https://app.asana.com/0/1201646897330968/1202050511506388
To Review: 
`git fetch origin pull/182/head:be/conditionals`
`git checkout be/conditionals`
`learn preview .`
> add section about pythonic conditionals

- exception-handling/checking-exceptions-in-tests.md
to address this feedback: https://app.asana.com/0/1201700438643002/1202601798209168/f
> add pytest learning goal

- config.yaml
Reverts Ada-Developers-Academy/core-unit-1#189
> Revert "Remove AC2 precourse essons from unit 1 config.yaml"

- exception-handling/problem-set-exception-handling.md
[asana ticket](https://app.asana.com/0/1201700438643002/1203024684909712/f)
Changed `ValueError` to `TypeError`
> Exception Handling Problem Set Typo Fix

- intro-to-tests/problem-set-intro-to-pytest.md
Fixing [this Asana Issue](https://app.asana.com/0/1201700438643002/1202980923319137/f).
Problem 14 in the Intro to Tests problem set is a bit of a trick question as it stands since you do not need to do a full implementation of determining if the input is odd, simply enough of an implementation for the test to pass.
I added a bit more of a hint to the question to write a _minimal_ implementation, as well as explaining why the answer is so minimal.
> Adding extra context to problem 14, to make it less of a trick question

- fundamentals/problem-set-conditionals.md
[Asana Ticket](https://app.asana.com/0/1201700438643002/1202976245489217/f)
Removed confusing sentence about promotions/discounts in the question #7 of the problem set with the help of @mikellewade!
> Removed verbiage about discounts from Fundamentals problem set 7 

- intro-to-tests/problem-set-intro-to-pytest.md
The following changes are intended to address [this Asana task](https://app.asana.com/0/1201700438643002/1202514475499725/f). 
The explanations for the exercises asking to identify the most accurate test name have been updated to be more specific.
> Update test name exercises explanations

- iterating-over-data/problem-set-iterating-over-data.md
- Deleted two problems that asked students to iterate over a dictionary to find the value associated with a key.
- Added a new problem that requires dictionary iteration but does not promote poor coding practices.
> Replace problems in iterating over data problem set.

- what-is-software-development/what-is-software.md
**Summary of Changes**
- Update wording to 'what is software' definition to clarify that code = instructions to a computer
- Add callout to highlight that software and program are largely interchangeable terms with slight differences
Part of Unit 1 'computer literacy' updates
> Clarify software v program definition

- intro-to-tests/automated-tests.md
**Summary of Changes**
- Remove dilbert comic
> Remove comic

- approaching-a-problem/intro-to-pair-programming.md
- fundamentals/math-primer.md
- fundamentals/problem-set-fundamentals-vocabulary.md
- intro-to-debugging/intro-to-debugging.md
- intro-to-dev-environment/problem-set-intro-to-dev-environment.md
- iterating-over-data/iterating-over-dictionaries.md
The changes in this PR address:
https://app.asana.com/0/1201700438643002/1204180997051127
https://app.asana.com/0/1201700438643002/1204181035752783
https://app.asana.com/0/1201700438643002/1204137893007038
https://app.asana.com/0/1201700438643002/1204159527708703
https://app.asana.com/0/1201700438643002/1204129834019938
https://app.asana.com/0/1201700438643002/1204130434251866
> Fix typos in Unit 1

- fundamentals/problem-set-conditionals.md
[Fundamentals, Problem Set: Conditionals, Challenge 8 vagueness](https://app.asana.com/0/1205655776549324/1202957476078398/f)
> Change problem from select all to multiple choice in Conditionals problem set

- fundamentals/problem-set-fundamentals-vocabulary.md
[Explanations for Problem Set: Fundamentals Vocabulary](https://app.asana.com/0/1205655776549324/1204113279723331/f)
> Add hints and explanations to questions 19-22

- config.yaml
Asana task: https://app.asana.com/0/1201700438643002/1209371073732995
> reorders Higher Order Functions to after OOP

- debugging-contd/problem-set-debugging-contd.md
[Asana ticket](https://app.asana.com/1/181459410160484/project/1205655776549324/task/1209694942622498?focus=true)
Update stack trace in question 4 of the Debugging, Cont. Problem Set to match the current line numbers of the repo.
> Debugging Cont. Problem set: Update stack trace to match changes to the repo

- fundamentals/conditionals.md
- intro-to-tests/automated-tests.md
Asana Tickets
- [Conditionals in Fundamentals - Remove Broken Link](https://app.asana.com/1/181459410160484/project/1205655776549324/task/1209600416514861?focus=true)
- [Intro to Automated Tests - Remove Broken Link](https://app.asana.com/1/181459410160484/project/1205655776549324/task/1209645389520607?focus=true)
Changes
- Fundamentals > Conditionals: Remove broken link. Update description into our own words. Add link to PEP 8 for further research into writing pythonic code
- Intro to Test > Intro to Automated Tests: Rephrase content and change link to a web archive of a tarot.com page with similar information.
> Fix broken links in Unit 1 lessons
